### ISSUE TITLE
No rule to make target modules stop in kali linux

### ISSUE THREAD

**Issue by johnnywalkers** [Braklet/rtl8811AU_rtl8821A-linux#2]
can use make. I get the error no rule to make target modules stop every time. Is there an update or change that I need to make to the Makefile?

**Comment by Braklet** [comment]
No idea as I switched to in-kernel drivers after upgrading to Ubuntu 14.04.  Haven't touched this driver in a long time.
B
 

    On Tuesday, June 13, 2017 1:24 AM, johnnywalkers <notifications@github.com> wrote:
 

 can use make. I get the error no rule to make target modules stop every time. Is there an update or change that I need to make to the Makefile?—
